'use client';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {extractCertificate,type Candidate} from '@/lib/pdf-import';
import {units,validPoint,fmt} from '@/lib/calibration';
export default function CertificateImport({username,password,version,dirty,onComplete}:{username:string;password:string;version:number;dirty:boolean;onComplete:()=>Promise<void>}){
 const [model,setModel]=useState('5522A'),[file,setFile]=useState<File|null>(null),[number,setNumber]=useState(''),[date,setDate]=useState(''),[records,setRecords]=useState<Candidate[]>([]),[warnings,setWarnings]=useState<string[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[page,setPage]=useState(1),[pdfUrl,setPdfUrl]=useState('');const cancel=useRef<AbortController|null>(null);
 const pages=[...new Set(records.map(r=>r.page))];
 async function read(){if(!file)return;if(file.size>20*1024*1024){setMessage('PDF limit: 20 MB.');return;}setBusy(true);setRecords([]);setWarnings([]);cancel.current=new AbortController();try{const result=await extractCertificate(file,model,setMessage,cancel.current.signal);setRecords(result.records);setWarnings(result.warnings);setPage(result.records[0].page);setMessage(`${result.records.length} candidate records. Check every page, including signs, units and coverage factor, before approving.`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function update(id:string,key:string,value:any){setRecords(v=>v.map(r=>r.id===id?{...r,[key]:value,checked:key==='checked'?value:false}:r));}
 async function commit(){setConfirm(false);if(!file)return;setBusy(true);try{const body=new FormData();body.set('file',file);body.set('model',model);body.set('number',number);body.set('date',date);body.set('version',String(version));body.set('records',JSON.stringify(records.map(({sourceText,checked,...p})=>p)));const res=await fetch('/api/certificates',{method:'POST',headers:{'x-record-password':password,'x-record-username':username},body});const data:any=await res.json();if(!res.ok)throw Error(data.error);await onComplete();setRecords([]);setMessage('Certificate approved. New → Old; uploaded certificate → New. The older Old records were removed.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const canCommit=!!username&&!!password&&!!file&&!!number.trim()&&!!date&&records.length>0&&records.every(r=>r.checked&&validPoint(r)&&r.uncertainty!==null)&&!dirty&&!busy;
 return <section className="panel certificate-import"><h2>Upload next calibration certificate</h2><p className="muted">PDF → review extracted records → approve with your record password. Each instrument has its own Old / New pair.</p><div className="selection-grid"><label className="field"><span>Reference</span><select value={model} disabled={busy||!!records.length} onChange={e=>setModel(e.target.value)}><option>5522A</option><option>8508A</option></select></label><label className="field"><span>Certificate number</span><Input value={number} disabled={busy} onChange={e=>setNumber(e.target.value)}/></label><label className="field"><span>Calibration date</span><Input type="date" value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>PDF · maximum 20 MB</span><Input type="file" accept="application/pdf,.pdf" disabled={busy} onChange={e=>{setRecords([]);setWarnings([]);setFile(e.target.files?.[0]||null);if(pdfUrl)URL.revokeObjectURL(pdfUrl);setPdfUrl(e.target.files?.[0]?URL.createObjectURL(e.target.files[0]):'');}}/></label></div><div className="actions"><Button onClick={read} disabled={!file||busy||!password||!username}>Extract PDF records</Button>{busy&&<Button variant="outline" onClick={()=>cancel.current?.abort()}>Cancel reading</Button>}{pdfUrl&&<a href={pdfUrl+'#page='+page} target="_blank" rel="noreferrer">Open PDF page {page}</a>}</div><p role="status" className="helper">{message}</p><p className="helper">Supports standard Fluke electrical tables. Scans use OCR; unreadable rows and unsupported sections are listed below. Review against every PDF page. U is absolute in the displayed unit; relative ppm values are converted using Ref. Confirm k from the certificate (initially 2).</p>
 {warnings.length>0&&<details className="import-warnings"><summary>{warnings.length} extraction notices — review omitted sections</summary>{warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}
 {!!records.length&&<><div className="actions"><label className="field"><span>Review PDF page</span><select value={page} onChange={e=>setPage(Number(e.target.value))}>{pages.map(p=><option key={p} value={p}>{p}</option>)}</select></label><span>{records.filter(r=>r.checked).length} / {records.length} verified</span><Button variant="outline" onClick={()=>setRecords(v=>v.map(r=>r.page===page?{...r,checked:true}:r))}>I checked all rows on this page</Button></div><Table><TableHeader><TableRow>{['Verified','Function / Range / Condition','Nominal',model==='5522A'?'Reference Value (UUC)':'Reference Value (Ref)',model==='5522A'?'Measurement Result (Ref)':'Measurement Result (UUC)','Expanded U','Unit','Hz / k','Source',''].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{records.filter(r=>r.page===page).map(r=><TableRow key={r.id}><TableCell><Checkbox checked={r.checked} aria-label={'Verify '+r.nominal} onCheckedChange={v=>update(r.id,'checked',v===true)}/></TableCell><TableCell>{(['fn','range','condition'] as const).map(key=><Input key={key} aria-label={key} value={r[key]} onChange={e=>update(r.id,key,e.target.value)}/>)}</TableCell>{(['nominal','reference','measured','uncertainty'] as const).map(key=><TableCell key={key}><Input type="number" step="any" aria-label={key} value={r[key]===null?'':Number((r[key]!/units[r.unit]).toPrecision(14))} onChange={e=>update(r.id,key,e.target.value===''?null:Number(e.target.value)*units[r.unit])}/></TableCell>)}<TableCell><select aria-label="Unit" value={r.unit} onChange={e=>{const u=e.target.value;setRecords(v=>v.map(p=>p.id===r.id?{...p,unit:u,nominal:p.nominal/units[p.unit]*units[u],reference:p.reference/units[p.unit]*units[u],measured:p.measured/units[p.unit]*units[u],uncertainty:p.uncertainty===null?null:p.uncertainty/units[p.unit]*units[u],checked:false}:p));}}>{Object.keys(units).map(u=><option key={u}>{u}</option>)}</select></TableCell><TableCell><Input aria-label="Frequency Hz" type="number" value={r.frequency??''} placeholder="DC" onChange={e=>update(r.id,'frequency',e.target.value===''?null:Number(e.target.value))}/><Input aria-label="Coverage factor" type="number" value={r.k} onChange={e=>update(r.id,'k',Number(e.target.value))}/></TableCell><TableCell><details><summary>Read text</summary><p>{r.sourceText}</p></details></TableCell><TableCell><Button variant="ghost" onClick={()=>setRecords(v=>v.filter(p=>p.id!==r.id))}>Remove</Button></TableCell></TableRow>)}</TableBody></Table><p className="helper">{dirty?'Save your workspace changes before importing.':`Approving will replace the ${model} certificate pair only. Calculations will use the newly approved data.`}</p><Button className="primary" disabled={!canCommit} onClick={()=>setConfirm(true)}>Approve certificate & update Old / New</Button></>}
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Approve {number} for {model}?</AlertDialogTitle><AlertDialogDescription>The current New becomes Old. The previous Old records are removed, and this PDF with {records.length} verified records becomes New. Other instruments are unchanged. Only the imported records will be available in the new certificate.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Back to review</AlertDialogCancel><AlertDialogAction onClick={commit}>Approve and replace</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>;
}
